/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionBD;
import Formularios.Clientes;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

// Importamos una libreria para hacer los botones mas esteticos
import FiveCod.utils.FCMaterialColors;
import FiveCod.utils.FCMaterialImageFactory;
import FiveCodLookAndFeelThemeV2.FiveCodMaterialLookAndFeel;
import FiveCodMaterialAnimation.FCMaterialUIMovement;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
/**
 *
 * @author artur
 */
public class ActualizarC extends javax.swing.JDialog {

    /**
     * Creates new form ActualizarC
     */
    public ActualizarC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarBotones_colores();
    }

    private void inicializarBotones_colores() {
    //  jButton1  
    btn_ActualizarC.setBackground(FCMaterialColors.GREEN_400);
    btn_ActualizarC.setForeground(Color.WHITE);
    btn_ActualizarC.addMouseListener(FCMaterialUIMovement.getMovement(btn_ActualizarC,FCMaterialColors.GREEN_400));
    btn_ActualizarC.setIcon(new ImageIcon(FCMaterialImageFactory.getIstance().getImage(FCMaterialImageFactory.FLOPPY_DRIVE)));
    
    btn_LimpiarAC.setBackground(FCMaterialColors.BLUE_400);
    btn_LimpiarAC.setForeground(Color.WHITE);
    btn_LimpiarAC.addMouseListener(FCMaterialUIMovement.getMovement(btn_LimpiarAC,FCMaterialColors.GREEN_400));
    
    btn_RegresarAC.setBackground(FCMaterialColors.BLUE_400);
    btn_RegresarAC.setForeground(Color.WHITE);
    btn_RegresarAC.addMouseListener(FCMaterialUIMovement.getMovement(btn_RegresarAC,FCMaterialColors.GREEN_400));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ACtxtID = new javax.swing.JTextField();
        ACtxtNombre = new javax.swing.JTextField();
        ACtxtApellidos = new javax.swing.JTextField();
        ACtxtTelefono = new javax.swing.JTextField();
        ACtxtDireccion = new javax.swing.JTextField();
        ACtxtEstado = new javax.swing.JTextField();
        ACtxtCorreo = new javax.swing.JTextField();
        btn_ActualizarC = new javax.swing.JButton();
        btn_LimpiarAC = new javax.swing.JButton();
        btn_RegresarAC = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actualizar registro de cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 27, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 95, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre(s):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 138, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellidos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 182, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 226, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 270, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 314, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 357, 110, -1));

        ACtxtID.setEditable(false);
        getContentPane().add(ACtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 95, 170, -1));
        getContentPane().add(ACtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 144, 170, -1));
        getContentPane().add(ACtxtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 188, 170, -1));
        getContentPane().add(ACtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 232, 170, -1));
        getContentPane().add(ACtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 276, 170, -1));
        getContentPane().add(ACtxtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 314, 170, -1));
        getContentPane().add(ACtxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 357, 170, -1));

        btn_ActualizarC.setText("Actualizar registro");
        btn_ActualizarC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ActualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarCActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ActualizarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 220, 71));

        btn_LimpiarAC.setText("Limpiar");
        btn_LimpiarAC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_LimpiarAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarACActionPerformed(evt);
            }
        });
        getContentPane().add(btn_LimpiarAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 100, 50));

        btn_RegresarAC.setText("Regresar");
        btn_RegresarAC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_RegresarAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarACActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RegresarAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 100, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/plano.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 350, 310));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/jordan azul chico.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ActualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarCActionPerformed
        // TODO add your handling code here:
        try{
      ConexionBD Con = new ConexionBD();
      Con.ConectarBD();
       String id = ACtxtID.getText();
       String nom = ACtxtNombre.getText();
       String ape = ACtxtApellidos.getText();
       String tel = ACtxtTelefono.getText();
       String dir = ACtxtDireccion.getText();
       String edo = ACtxtEstado.getText();
       String correo = ACtxtCorreo.getText();
       String SQL = "UPDATE clientes SET nombres='"+nom+"',apellidos='"+ape+"',telefono='"+tel+"',"
               + "direccion='"+dir+"',estado='"+edo+"',"
               + "correo='"+correo+"'"
               + "WHERE id ='"+id+"'";
       Con.sentencia.execute(SQL);
       JOptionPane.showMessageDialog(null,
               "¡Registro Actualizado con Éxito!");
       Con.DesconectarBD();
  }catch (SQLException ex) {
      Logger.getLogger(ActualizarC.class.getName()).log(Level.SEVERE, null, ex);
  }
    }//GEN-LAST:event_btn_ActualizarCActionPerformed

    private void btn_LimpiarACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarACActionPerformed
       ACtxtNombre.setText("");
       ACtxtApellidos.setText("");
       ACtxtTelefono.setText("");
       ACtxtDireccion.setText("");
       ACtxtEstado.setText("");
       ACtxtCorreo.setText("");
    }//GEN-LAST:event_btn_LimpiarACActionPerformed

    private void btn_RegresarACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarACActionPerformed
        Clientes clientes = new Clientes();
        clientes.setVisible(true);
        
    }//GEN-LAST:event_btn_RegresarACActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FiveCodMaterialLookAndFeel());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_BIENVENIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizarC dialog = new ActualizarC(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ACtxtApellidos;
    public javax.swing.JTextField ACtxtCorreo;
    public javax.swing.JTextField ACtxtDireccion;
    public javax.swing.JTextField ACtxtEstado;
    public javax.swing.JTextField ACtxtID;
    public javax.swing.JTextField ACtxtNombre;
    public javax.swing.JTextField ACtxtTelefono;
    private javax.swing.JButton btn_ActualizarC;
    private javax.swing.JButton btn_LimpiarAC;
    private javax.swing.JButton btn_RegresarAC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
