/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionBD;
import Formularios.Clientes;
import Formularios.Ventas;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

// Importamos una libreria para hacer los botones mas esteticos
import FiveCod.utils.FCMaterialColors;
import FiveCod.utils.FCMaterialImageFactory;
import FiveCodLookAndFeelThemeV2.FiveCodMaterialLookAndFeel;
import FiveCodMaterialAnimation.FCMaterialUIMovement;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author artur
 */
public class ActualizarV extends javax.swing.JDialog {

    /**
     * Creates new form ActualizarV
     */
    public ActualizarV(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarBotones_colores();
    }

    private void inicializarBotones_colores() {
        //  jButton1  
        btn_ActualizarC.setBackground(FCMaterialColors.BLUE_400);
        btn_ActualizarC.setForeground(Color.WHITE);
        btn_ActualizarC.addMouseListener(FCMaterialUIMovement.getMovement(btn_ActualizarC, FCMaterialColors.GREEN_400));
        btn_ActualizarC.setIcon(new ImageIcon(FCMaterialImageFactory.getIstance().getImage(FCMaterialImageFactory.FLOPPY_DRIVE)));
        
        btn_LimpiarAV.setBackground(FCMaterialColors.BLUE_400);
        btn_LimpiarAV.setForeground(Color.WHITE);
        btn_LimpiarAV.addMouseListener(FCMaterialUIMovement.getMovement(btn_LimpiarAV, FCMaterialColors.GREEN_400));
        
        btn_RegresarAV.setBackground(FCMaterialColors.BLUE_400);
        btn_RegresarAV.setForeground(Color.WHITE);
        btn_RegresarAV.addMouseListener(FCMaterialUIMovement.getMovement(btn_RegresarAV, FCMaterialColors.GREEN_400));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AVtxtID = new javax.swing.JTextField();
        AVtxtidCliente = new javax.swing.JTextField();
        AVtxtidProducto = new javax.swing.JTextField();
        AVtxtFecha = new javax.swing.JTextField();
        AVtxtTotal = new javax.swing.JTextField();
        btn_ActualizarC = new javax.swing.JButton();
        AVtxtFormaPago = new javax.swing.JTextField();
        btn_LimpiarAV = new javax.swing.JButton();
        btn_RegresarAV = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Actualizar registro de ventas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("idCliente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("idProducto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Forma de Pago:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        AVtxtID.setEditable(false);
        getContentPane().add(AVtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 180, -1));
        getContentPane().add(AVtxtidCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 180, -1));
        getContentPane().add(AVtxtidProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 180, -1));
        getContentPane().add(AVtxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 180, -1));
        getContentPane().add(AVtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 180, -1));

        btn_ActualizarC.setText("Actualizar registro:");
        btn_ActualizarC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ActualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarCActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ActualizarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 190, 60));
        getContentPane().add(AVtxtFormaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 180, -1));

        btn_LimpiarAV.setText("Limpiar");
        btn_LimpiarAV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_LimpiarAV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarAVActionPerformed(evt);
            }
        });
        getContentPane().add(btn_LimpiarAV, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 90, 50));

        btn_RegresarAV.setText("Regresar");
        btn_RegresarAV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_RegresarAV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarAVActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RegresarAV, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 120, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/plano.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 380, 280));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/jordan azul chico.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ActualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarCActionPerformed
        // TODO add your handling code here:
        try {
            ConexionBD Con = new ConexionBD();
            Con.ConectarBD();
            String id = AVtxtID.getText();
            String idCliente = AVtxtidCliente.getText();
            String idProducto = AVtxtidProducto.getText();
            String fecha = AVtxtFecha.getText();
            String total = AVtxtTotal.getText();
            String formaPago = AVtxtFormaPago.getText();
            //String formaPago = AVcbxFormaPago.getSelectedItem().toString();

            String SQL = "UPDATE ventas SET idCliente='" + idCliente + "',idProducto='" + idProducto + "',fecha='" + fecha + "',"
                    + "total='" + total + "',formaPago='" + formaPago + "'"
                    + "WHERE id ='" + id + "'";
            Con.sentencia.execute(SQL);
            JOptionPane.showMessageDialog(null,
                    "¡Registro Actualizado con Éxito!");
            Con.DesconectarBD();
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ActualizarCActionPerformed

    private void btn_RegresarAVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarAVActionPerformed
        // TODO add your handling code here:
        Ventas ventas = new Ventas();
        ventas.setVisible(true);
    }//GEN-LAST:event_btn_RegresarAVActionPerformed

    private void btn_LimpiarAVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarAVActionPerformed
        // TODO add your handling code here:
            AVtxtidCliente.setText("");
            AVtxtidProducto.setText("");
            AVtxtFecha.setText("");
            AVtxtTotal.setText("");
            AVtxtFormaPago.setText("");
    }//GEN-LAST:event_btn_LimpiarAVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FiveCodMaterialLookAndFeel());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_BIENVENIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizarV dialog = new ActualizarV(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AVtxtFecha;
    public javax.swing.JTextField AVtxtFormaPago;
    public javax.swing.JTextField AVtxtID;
    public javax.swing.JTextField AVtxtTotal;
    public javax.swing.JTextField AVtxtidCliente;
    public javax.swing.JTextField AVtxtidProducto;
    private javax.swing.JButton btn_ActualizarC;
    private javax.swing.JButton btn_LimpiarAV;
    private javax.swing.JButton btn_RegresarAV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
