/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
// Importamos una libreria para hacer los botones mas esteticos
import FiveCod.utils.FCMaterialColors;
import FiveCod.utils.FCMaterialImageFactory;
import FiveCodLookAndFeelThemeV2.FiveCodMaterialLookAndFeel;
import FiveCodMaterialAnimation.FCMaterialUIMovement;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import Formularios.INVENTARIOS;
import Formularios.Ventas;
/**
 *
 * @author luiss
 */
public class FORM_BIENVENIDA extends javax.swing.JFrame {

    /**
     * Creates new form FORM_BIENVENIDA
     */
    public FORM_BIENVENIDA() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarBotones_colores();
    }

    private void inicializarBotones_colores() {
    //  jButton1  
    GESTIONAR_INVENTARIO.setBackground(FCMaterialColors.GREEN_400);
    GESTIONAR_INVENTARIO.setForeground(Color.WHITE);
    GESTIONAR_INVENTARIO.addMouseListener(FCMaterialUIMovement.getMovement(GESTIONAR_INVENTARIO,FCMaterialColors.ORANGE_500));
    GESTIONAR_INVENTARIO.setIcon(new ImageIcon(FCMaterialImageFactory.getIstance().getImage(FCMaterialImageFactory.FLOPPY_DRIVE)));
        //  jButton1  
    GESTION_VENTAS.setBackground(FCMaterialColors.GREEN_400);
    GESTION_VENTAS.setForeground(Color.WHITE);
    GESTION_VENTAS.addMouseListener(FCMaterialUIMovement.getMovement(GESTION_VENTAS,FCMaterialColors.ORANGE_500));
    GESTION_VENTAS.setIcon(new ImageIcon(FCMaterialImageFactory.getIstance().getImage(FCMaterialImageFactory.FLOPPY_DRIVE)));
        //  jButton1  
    GESTION_CLIENTES.setBackground(FCMaterialColors.GREEN_400);
    GESTION_CLIENTES.setForeground(Color.WHITE);
    GESTION_CLIENTES.addMouseListener(FCMaterialUIMovement.getMovement(GESTION_CLIENTES,FCMaterialColors.ORANGE_500));
    GESTION_CLIENTES.setIcon(new ImageIcon(FCMaterialImageFactory.getIstance().getImage(FCMaterialImageFactory.FLOPPY_DRIVE)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GESTIONAR_INVENTARIO = new javax.swing.JButton();
        GESTION_CLIENTES = new javax.swing.JButton();
        GESTION_VENTAS = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿QUE HAREMOS HOY?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        GESTIONAR_INVENTARIO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GESTIONAR_INVENTARIO.setForeground(new java.awt.Color(255, 255, 255));
        GESTIONAR_INVENTARIO.setText("GESTIONAR INVENTARIO");
        GESTIONAR_INVENTARIO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GESTIONAR_INVENTARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GESTIONAR_INVENTARIOMouseClicked(evt);
            }
        });
        GESTIONAR_INVENTARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GESTIONAR_INVENTARIOActionPerformed(evt);
            }
        });
        jPanel1.add(GESTIONAR_INVENTARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 340, 63));
        GESTIONAR_INVENTARIO.getAccessibleContext().setAccessibleName("TABLA_CLIENTES");

        GESTION_CLIENTES.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GESTION_CLIENTES.setText("GESTIONAR CLIENTES");
        GESTION_CLIENTES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GESTION_CLIENTES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GESTION_CLIENTESMouseClicked(evt);
            }
        });
        jPanel1.add(GESTION_CLIENTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 340, 63));

        GESTION_VENTAS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GESTION_VENTAS.setText("GESTIONAR DE VENTAS");
        GESTION_VENTAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GESTION_VENTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GESTION_VENTASActionPerformed(evt);
            }
        });
        jPanel1.add(GESTION_VENTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 340, 63));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/logo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 100, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/jordan azul chico.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -5, 590, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GESTIONAR_INVENTARIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GESTIONAR_INVENTARIOMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_GESTIONAR_INVENTARIOMouseClicked

    private void GESTION_CLIENTESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GESTION_CLIENTESMouseClicked
        // TODO add your handling code here:
        Clientes clientes=new Clientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_GESTION_CLIENTESMouseClicked

    private void GESTIONAR_INVENTARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GESTIONAR_INVENTARIOActionPerformed
        // TODO add your handling code here:
        INVENTARIOS inventario = new INVENTARIOS();
        inventario.setVisible(true);
    }//GEN-LAST:event_GESTIONAR_INVENTARIOActionPerformed

    private void GESTION_VENTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GESTION_VENTASActionPerformed
        // TODO add your handling code here:
        Ventas ventas = new Ventas();
        ventas.setVisible(true);
    }//GEN-LAST:event_GESTION_VENTASActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FiveCodMaterialLookAndFeel());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_BIENVENIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_BIENVENIDA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GESTIONAR_INVENTARIO;
    private javax.swing.JButton GESTION_CLIENTES;
    private javax.swing.JButton GESTION_VENTAS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
