/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionBD;
import java.sql.SQLException;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.logging.PlatformLogger;
import sun.util.logging.PlatformLogger.Level;
import Formularios.FORM_BIENVENIDA;

// Importamos una libreria para hacer los botones mas esteticos
import FiveCod.utils.FCMaterialColors;
import FiveCod.utils.FCMaterialImageFactory;
import FiveCodLookAndFeelThemeV2.FiveCodMaterialLookAndFeel;
import FiveCodMaterialAnimation.FCMaterialUIMovement;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
/**
 *
 * @author artur
 */
public class Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        Crear_Modelo();
        this.setLocationRelativeTo(null);
        inicializarBotones_colores();
    }

    private void inicializarBotones_colores() {
        //  jButton1  
        btnGuardar.setBackground(FCMaterialColors.GREEN_400);
        btnGuardar.setForeground(Color.WHITE);
        btnGuardar.addMouseListener(FCMaterialUIMovement.getMovement(btnGuardar, FCMaterialColors.GREEN_400));
        btnGuardar.setIcon(new ImageIcon(FCMaterialImageFactory.getIstance().getImage(FCMaterialImageFactory.FLOPPY_DRIVE)));
        //  jButton1  
        btnLimpiar.setBackground(FCMaterialColors.BLUE_400);
        btnLimpiar.setForeground(Color.WHITE);
        btnLimpiar.addMouseListener(FCMaterialUIMovement.getMovement(btnLimpiar, FCMaterialColors.GREEN_400));
        btnLimpiar.setIcon(new ImageIcon(FCMaterialImageFactory.getIstance().getImage(FCMaterialImageFactory.FLOPPY_DRIVE)));
        //  jButton1  
        btnConsultar.setBackground(FCMaterialColors.GREEN_400);
        btnConsultar.setForeground(Color.WHITE);
        btnConsultar.addMouseListener(FCMaterialUIMovement.getMovement(btnConsultar, FCMaterialColors.GREEN_400));
        btnConsultar.setIcon(new ImageIcon(FCMaterialImageFactory.getIstance().getImage(FCMaterialImageFactory.FLOPPY_DRIVE)));
        //  jButton1  
        btnActualizar.setBackground(FCMaterialColors.GREEN_400);
        btnActualizar.setForeground(Color.WHITE);
        btnActualizar.addMouseListener(FCMaterialUIMovement.getMovement(btnActualizar, FCMaterialColors.GREEN_400));
        btnActualizar.setIcon(new ImageIcon(FCMaterialImageFactory.getIstance().getImage(FCMaterialImageFactory.FLOPPY_DRIVE)));
        //  jButton1  
        btnEliminar.setBackground(FCMaterialColors.RED_400);
        btnEliminar.setForeground(Color.WHITE);
        btnEliminar.addMouseListener(FCMaterialUIMovement.getMovement(btnEliminar, FCMaterialColors.RED_400));
        btnEliminar.setIcon(new ImageIcon(FCMaterialImageFactory.getIstance().getImage(FCMaterialImageFactory.FLOPPY_DRIVE)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtidProducto = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtidCliente = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Ventas = new javax.swing.JTable();
        cbxFormaPago = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtidProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 213, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, -1, -1));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 213, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 580, -1, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 213, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Forma de pago:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("id del Cliente:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("id del Producto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestión de Ventas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 11, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 100, 50));
        getContentPane().add(txtidCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 213, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 110, 50));

        Tabla_Ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tabla_Ventas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 72, 871, 492));

        cbxFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "credito", "debito", "efectivo" }));
        getContentPane().add(cbxFormaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1340, 370));

        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 110, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/plano.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, 220));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondo jordan azul.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ConexionBD Con = new ConexionBD();
        Con.ConectarBD();
        String fecha, formaPago, idCliente, idProducto, total;
        
        idCliente = txtidCliente.getText();
        idProducto = txtidProducto.getText();
        fecha = txtFecha.getText();
        total = txtTotal.getText();
        formaPago = cbxFormaPago.getSelectedItem().toString();
        if (!idCliente.isEmpty()) {
                if (!idProducto.isEmpty()) {
                    if (!fecha.isEmpty()) {
                        if (!total.isEmpty()) {
                            if (!formaPago.isEmpty()) {
                                
                                        try {
                                            String SQL = "INSERT INTO ventas"
                                                    + "(idCliente,idProducto,fecha,total,formaPago)"
                                                    + " VALUES "
                                                    + "('" + idCliente + "','" + idProducto + "','" + fecha + "','" + total + "','" + formaPago +"');";
                                            Con.sentencia.execute(SQL);
                                            JOptionPane.showMessageDialog(null, "¡Los datos fueron guardados con éxito!");
                                        } catch (SQLException ex) {
                                            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                                        }
                               
                            } else {
                                JOptionPane.showMessageDialog(null, "Por favor ingrese la forma de pago");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Por favor ingrese el total del pago");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor ingrese la fecha");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor ingrese el id del producto");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese el id del cliente");
        }
        Con.DesconectarBD();
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
       Consultar();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String ID = Tabla_Ventas.getValueAt(Tabla_Ventas.getSelectedRow(), 0).toString();
        String idCliente = Tabla_Ventas.getValueAt(Tabla_Ventas.getSelectedRow(), 1).toString();
        String idProducto = Tabla_Ventas.getValueAt(Tabla_Ventas.getSelectedRow(), 2).toString();
        String fecha = Tabla_Ventas.getValueAt(Tabla_Ventas.getSelectedRow(), 3).toString();
        String total = Tabla_Ventas.getValueAt(Tabla_Ventas.getSelectedRow(), 4).toString();
        String formaPago = Tabla_Ventas.getValueAt(Tabla_Ventas.getSelectedRow(), 5).toString();
        
        ActualizarV Act = new ActualizarV(null, true);
        Act.AVtxtID.setText(ID);
        Act.AVtxtidCliente.setText(idCliente);
        Act.AVtxtidProducto.setText(idProducto);
        Act.AVtxtFecha.setText(fecha);
        Act.AVtxtTotal.setText(total);
        Act.AVtxtFormaPago.setText(formaPago);
        //Act.AVcbxFormaPago.setSelectedItem(Tabla_Ventas.getValueAt(Tabla_Ventas.getSelectedRow(), 5));
        Act.setVisible(true);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       try{
            String ID = Tabla_Ventas.getValueAt(Tabla_Ventas.getSelectedRow(), 0).toString();
            ConexionBD Con = new ConexionBD();
            Con.ConectarBD();;
            String SQL = "DELETE FROM ventas WHERE id='"+ID+"'";
            Con.sentencia.execute(SQL);
            JOptionPane.showMessageDialog(null, "¡El registro fue eliminado!");
            Con.DesconectarBD();
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtidCliente.setText("");
        txtidProducto.setText("");
        txtFecha.setText("");
        txtTotal.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
         FORM_BIENVENIDA bienvenida = new FORM_BIENVENIDA();
        bienvenida.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }
     //CONSULTAR REGISTROS 
    DefaultTableModel modelo;

    private void Crear_Modelo() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                         "ID", "idCliente", "idProducto", "fecha",
                        "total", "Forma de Pago"}) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class,
                    
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false};

                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            Tabla_Ventas.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "Error");
        }
    }

    private void Consultar() {
        try {
            int i = 0;
            Object Ob[] = null;
            ConexionBD Con = new ConexionBD();
            Con.ConectarBD();
            String SQL = "SELECT * FROM ventas";
            Con.resultado = Con.sentencia.executeQuery(SQL);
            while (Con.resultado.next()) {
                modelo.addRow(Ob);
                modelo.setValueAt(Con.resultado.getString("id"), i, 0);
                modelo.setValueAt(Con.resultado.getString("idCliente"), i, 1);
                modelo.setValueAt(Con.resultado.getString("idProducto"), i, 2);
                modelo.setValueAt(Con.resultado.getString("fecha"), i, 3);
                modelo.setValueAt(Con.resultado.getString("total"), i, 4);
                modelo.setValueAt(Con.resultado.getString("formaPago"), i, 5);
               
                i++;
            }
            Con.DesconectarBD();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Ventas;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxFormaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtidCliente;
    private javax.swing.JTextField txtidProducto;
    // End of variables declaration//GEN-END:variables
}
